### ISSUE TITLE
Python yara.load read from variable

### ISSUE THREAD

**Issue by ricardo-dias** [plusvic/yara#153]
This is a feature request, about the possibility of yara.load to read from a variable in the same manner yara.compile with 'sources'. The idea is to load compiled rules fetched via HTTP.

**Comment by hillu** [comment]
I have just pushed the C foundation for this feature to https://github.com/hillu/yara/tree/stream and verified that a feature like reading compiled rules from an in-memory buffer or through a HTTP client could be implemented on top of this within go-yara (https://github.com/hillu/go-yara)

Victor, please tell me if this is what you had in mind and I'll take a stab at enhancing the Python bindings

**Comment by Neo23x0** [comment]
This .. is .. awesome. 
Let's hope that this feature finds its way into a stable release. We Python programmers need this in order to allow us a secure deployment of rules without writing them to disk before they can be initialized.

**Comment by plusvic** [comment]
Great! It looks like a good approach, we can have a single implementation of yr_arena_load reading from the YR_STREAM abstraction, and then two implementations of YR_STREAM, one reading from an actual file and the other reading from a buffer. That's what you have in mind? Would you like to keep working on it? I'll happily merge it when you're done.

**Comment by hillu** [comment]
* Victor M. Alvarez:

> Great! It looks like a good approach, we can have a single
> implementation of yr_arena_load reading from the YR_STREAM
> abstraction, and then two implementations of YR_STREAM, one reading
> from an actual file and the other reading from a buffer. 

That was pretty much my idea, yes.

I have just replaced yr_rules_load (because that's what is exposed to
the user) with an implementation that uses a YR_STREAM where the read
method is fread(). See
<https://github.com/hillu/yara/commit/9b2debfbf0708a1dc6d0c84f2986a77bd171ce96>

NB: One thing that does not work when working with only an fread()
interface is getting the file size to do sanity checks as is currently
done in yr_arena_load():

    fseek(fh, 0, SEEK_END);
    file_size = ftell(fh);
    fseek(fh, 0, SEEK_SET);

I don't think that this is a bad problem, though: If header.size bytes
can't be read into the page, this is detected as an error.

> Would you like to keep working on it? I'll happily merge it when
> you're done.

Sure. I'll try to get the C/Python API to play nice, add some tests, and
let you know.

Cheers,
-Hilko

**Comment by hillu** [comment]
I integrated YR_STREAM into the yara.load method -- which now accepts either a filename or a "file-like object". Simple test using StringIO included. See https://github.com/hillu/yara/tree/stream

Cheers,
-Hilko

**Comment by hillu** [comment]
Thank you for your quick reaction. The write support that you added afterwards is *exactly* what I had in mind. :-)

Cheers,
-Hilko

**Comment by plusvic** [comment]
You had in mind write support too! I should have wait :-)
