### ISSUE TITLE
Entrypoint bug (DEF) 

### ISSUE THREAD

**Issue by Chandlr** [plusvic/yara#395]
sample file:
https://mega.nz/#!FQlzSDwZ!dPpDd9OQWBbyKLCkGf6YBvI_PIpe-ZCcZurfKnnSSVs

this signature should work but it doest:

rule DEF10 : bart xt
{
		meta:
		author="_pusher_"
		date = "2015-11"
	strings:
		$a0 = { BE ?? ?? ?? ?? 6A ?? 59 80 7E 07 00 74 11 8B 46 0C 05 00 00 40 00 8B 56 10 30 10 40 4A 75 FA 83 C6 28 E2 E4 68 ?? ?? ?? ?? C3 }
	condition:
		$a0 at pe.entry_point
}

**Comment by wxsBSD** [comment]
What makes you think this should work? What do you believe the entry_point to be (as an offset into the file, please)? I can't even get the sample to execute.

**Comment by Chandlr** [comment]
Iam on Win7 Ultimate x64 works fine here
well the offset is: 220
and 
00400220 | BE A8 01 40 00           | mov esi,def.4001A8                      | ;4001A8:".def"
in x64dbg
i dont know what offset yara gives tho

**Comment by hillu** [comment]
@wxsBSD The sample can be executed on XP, OllyDbg on XP ends up with the EP at 0x00400220 with the same contents as can be found at 0x220 into the file.

YARA sets `pe.entry_point` to -1 because offset 0x220 is not inside any of the defined sections. I think that `pe_rva_to_offset` needs to learn some more tricks. :-)

**Comment by plusvic** [comment]
Fixed in ba60f4e5edd4d1eca9ba2f1ad6f5543aa4d95153
